package org.example;// Generated by Selenium IDE

import com.aventstack.extentreports.ExtentReports;
import com.aventstack.extentreports.ExtentTest;
import com.aventstack.extentreports.reporter.ExtentHtmlReporter;
import org.junit.*;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.Map;

public class SuitTest {
    private static WebDriver driver;
    private static Map<String, Object> vars;
    private static ExtentTest extentTest;
    private static ExtentReports reports  ;

    @BeforeClass
    public static  void setup(){

        ExtentHtmlReporter htmlReporter = new ExtentHtmlReporter("Report.html");
        reports = new ExtentReports();
        reports.attachReporter(htmlReporter);

        driver = new ChromeDriver();
        vars = new HashMap<String, Object>();
        extentTest = reports.createTest("Test");


    }
    @AfterClass
    public static  void tearDown() {
        driver.quit();
    }

//    @Before
//    public void setUpReport() {
//        ExtentHtmlReporter htmlReporter = new ExtentHtmlReporter("Report.html");
//        reports = new ExtentReports();
//        reports.attachReporter(htmlReporter);


//    }
    @After
    public void tearDownReport() {
        if (reports != null) {
            reports.flush();
        }
    }

    @Test
    public void amountEmpty() {
//        driver = new ChromeDriver();
//        vars = new HashMap<String, Object>();
//        extentTest = reports.createTest("Test","test 1");
        driver.get("http://127.0.0.1:5500/index.html");
        driver.manage().window().setSize(new Dimension(786, 816));
        driver.findElement(By.id("from")).click();
        {
            WebElement dropdown = driver.findElement(By.id("from"));
            dropdown.findElement(By.xpath("//option[. = 'JOD']")).click();
        }
        driver.findElement(By.id("to")).click();
        {
            WebElement dropdown = driver.findElement(By.id("to"));
            dropdown.findElement(By.xpath("//option[. = 'ILS']")).click();
        }
        driver.findElement(By.id("convert")).click();

        extentTest.pass("Success");
//        driver.quit();


    }

    @Test
    public void fromEmpty() {
//        driver = new ChromeDriver();
//        vars = new HashMap<String, Object>();
//        extentTest = reports.createTest("Test1");
        driver.get("http://127.0.0.1:5500//index.html");
        driver.manage().window().setSize(new Dimension(788, 816));
        driver.findElement(By.id("amount")).click();
        driver.findElement(By.id("amount")).sendKeys("1000");
        driver.findElement(By.id("to")).click();
        {
            WebElement dropdown = driver.findElement(By.id("to"));
            dropdown.findElement(By.xpath("//option[. = 'ILS']")).click();
        }
        driver.findElement(By.id("convert")).click();
        extentTest.pass("Success");
//        driver.quit();
    }
    @Test
    public void minusAmount() {
//        driver = new ChromeDriver();
//        vars = new HashMap<String, Object>();
//        extentTest = reports.createTest("Test2");
        driver.get("http://127.0.0.1:5500//index.html");
        driver.manage().window().setSize(new Dimension(786, 816));
        driver.findElement(By.id("amount")).click();
        driver.findElement(By.id("amount")).sendKeys("-1555");
        driver.findElement(By.id("from")).click();
        {
            WebElement dropdown = driver.findElement(By.id("from"));
            dropdown.findElement(By.xpath("//option[. = 'JOD']")).click();
        }
        driver.findElement(By.id("to")).click();
        {
            WebElement dropdown = driver.findElement(By.id("to"));
            dropdown.findElement(By.xpath("//option[. = 'EUR']")).click();
        }
        driver.findElement(By.id("convert")).click();
        extentTest.pass("Success");
//        driver.quit();

    }
    @Test
    public void runTest() {
//        driver = new ChromeDriver();
//        vars = new HashMap<String, Object>();
//        extentTest = reports.createTest("Test3");
        driver.get("http://127.0.0.1:5500//index.html");
        driver.manage().window().setSize(new Dimension(786, 816));
        driver.findElement(By.id("amount")).click();
        driver.findElement(By.id("amount")).sendKeys("100");
        driver.findElement(By.cssSelector(".container")).click();
        driver.findElement(By.id("from")).click();
        {
            WebElement dropdown = driver.findElement(By.id("from"));
            dropdown.findElement(By.xpath("//option[. = 'USD']")).click();
        }
        driver.findElement(By.id("to")).click();
        {
            WebElement dropdown = driver.findElement(By.id("to"));
            dropdown.findElement(By.xpath("//option[. = 'ILS']")).click();
        }
        driver.findElement(By.id("convert")).click();
        extentTest.pass("Success");
//        driver.quit();
    }
    @Test
    public void toEmpty() {
//        driver = new ChromeDriver();
//        vars = new HashMap<String, Object>();
//        extentTest = reports.createTest("Test4");
        driver.get("http://127.0.0.1:5500//index.html");
        driver.manage().window().setSize(new Dimension(788, 816));
        driver.findElement(By.id("amount")).click();
        driver.findElement(By.id("amount")).sendKeys("10000");
        driver.findElement(By.id("from")).click();
        {
            WebElement dropdown = driver.findElement(By.id("from"));
            dropdown.findElement(By.xpath("//option[. = 'ILS']")).click();
        }
        driver.findElement(By.id("convert")).click();
        extentTest.pass("Success");
//        driver.quit();
    }
}

